// Central RBAC Reference Data tailored for Contract Repository System (CRS) - BSI Maslahat
export const RBAC_MODULES = [
  "PKS & KONTRAK",
  "DOKUMEN & VERSI",
  "LEGAL & COMPLIANCE",
  "DUAL REVIEW MODE",
  "WATERMARKING ENGINE",
  "SMART GUIDELINES",
  "REMINDER & KEDALUWARSA",
  "DASBOR & ANALITIK",
  "LAPORAN & EKSPOR",
  "TATA KELOLA PENGGUNA",
  "AUDIT TRAIL & FORENSIK",
  "SISTEM & INTEGRASI",
];

// Raw definition of CRS Roles across BSI Maslahat Organization
const RAW_ROLES = [
  {
    id: "super_admin",
    name: "Super Administrator (IT Admin)",
    desc: "Akses konfigurasi infrastruktur sistem, kelola akun pengguna, pengawasan kebijakan keamanan, dan jejak audit global tanpa wewenang mengubah klausul kontrak.",
    outsideCatalog: 1,
  },
  {
    id: "legal_officer",
    name: "Legal Officer (LCG)",
    desc: "Tim ahli hukum Legal & Compliance Group yang memimpin telaah ganda, injeksi watermark hasil reviu, approval legalitas draf, verifikasi scan fisik tandatangan, dan aktivasi PKS.",
    outsideCatalog: 0,
  },
  {
    id: "business_unit",
    name: "Business Unit (Inisiator Umum)",
    desc: "Unit kerja pemrakarsa kerja sama yang bertugas menyusun formulir awal PKS, ekstraksi metadata dokumen .docx, dan unggah berkas scan tanda tangan fisik offline.",
    outsideCatalog: 0,
  },
  {
    id: "bu_crg",
    name: "Business Unit - CRG",
    desc: "Corporate Relationship Group pemrakarsa kemitraan strategis korporasi, pengelolaan PIC mitra perusahaan, dan monitoring masa berlaku PKS korporat.",
    outsideCatalog: 0,
  },
  {
    id: "bu_dfg",
    name: "Business Unit - DFG",
    desc: "Digital & Funding Group inisiator draf PKS platform digital, payment gateway QRIS/Fintech, dan kerja sama penghimpunan dana digital.",
    outsideCatalog: 0,
  },
  {
    id: "bu_mcg",
    name: "Business Unit - MCG",
    desc: "Marketing Communication Group pemrakarsa kerja sama publikasi, media promosi, sponsorship program kemaslahatan, dan periklanan.",
    outsideCatalog: 0,
  },
  {
    id: "bu_rng",
    name: "Business Unit - RNG",
    desc: "Regional Network Group inisiator kemitraan jaringan perwakilan wilayah dan unit kantor cabang Bank Syariah Indonesia (BSI).",
    outsideCatalog: 0,
  },
  {
    id: "bu_pgg",
    name: "Business Unit - PGG",
    desc: "Partnership & Government Group pemrakarsa kerja sama instansi kementerian, dinas pemerintah, dan badan usaha milik negara (BUMN).",
    outsideCatalog: 0,
  },
  {
    id: "bu_cag",
    name: "Business Unit - CAG",
    desc: "Consumer & Asset Group inisiator kemitraan pengelolaan aset lembaga, konsumen ritel, dan pemanfaatan properti kemaslahatan.",
    outsideCatalog: 0,
  },
  {
    id: "bu_idg",
    name: "Business Unit - IDG (IT & Digital Group)",
    desc: "IT & Digital Group pemrakarsa kemitraan teknologi informasi, lisensi software, platform digital, integrasi API perbankan syariah, dan infrastruktur sistem.",
    outsideCatalog: 0,
  },
  {
    id: "bu_wag",
    name: "Business Unit - WAG",
    desc: "Waqf Asset Group inisiator kerja sama wakaf uang, aset wakaf produktif, dan sertifikasi kemitraan nazhir wakaf.",
    outsideCatalog: 0,
  },
  {
    id: "bu_smg",
    name: "Business Unit - SMG",
    desc: "Social & Micro Group inisiator kemitraan program pemberdayaan ekonomi mikro, usaha ultra mikro, dan mustahik binaan.",
    outsideCatalog: 0,
  },
  {
    id: "bu_fsg",
    name: "Business Unit - FSG",
    desc: "Financial Services Group inisiator perjanjian layanan jasa perbankan syariah, asuransi syariah, dan penempatan likuiditas dana.",
    outsideCatalog: 0,
  },
  {
    id: "bu_leg",
    name: "Business Unit - LEG",
    desc: "Logistics & Enterprise Group inisiator perjanjian pengadaan inventaris, logistik operasional, dan vendor perusahaan.",
    outsideCatalog: 0,
  },
  {
    id: "bu_csg",
    name: "Business Unit - CSG",
    desc: "Corporate Secretary Group inisiator administrasi kesekretariatan korporat, notaris rekanan, dan arsip legal korporasi.",
    outsideCatalog: 0,
  },
  {
    id: "bu_hcg",
    name: "Business Unit - HCG",
    desc: "Human Capital Group inisiator kerja sama ketenagakerjaan, penyedia tenaga alih daya (outsourcing), asuransi kesehatan pegawai, dan pelatihan.",
    outsideCatalog: 0,
  },
  {
    id: "bu_bcg",
    name: "Business Unit - BCG",
    desc: "Business Commercial Group inisiator aliansi bisnis komersial dan skema kerja sama mutualisme BSI Maslahat.",
    outsideCatalog: 0,
  },
  {
    id: "bu_edg",
    name: "Business Unit - EDG",
    desc: "Executive Director Group inisiator perjanjian tingkat direksi, kerja sama lembaga internasional, dan donor multilateral.",
    outsideCatalog: 0,
  },
  {
    id: "management",
    name: "Manajemen Eksekutif (Direksi & Kadiv)",
    desc: "Pimpinan eksekutif yang memerlukan visibilitas helikopter menyeluruh terhadap kinerja portofolio PKS, pemantauan masa kedaluwarsa, dan ekspor laporan.",
    outsideCatalog: 0,
  },
  {
    id: "auditor_internal",
    name: "Auditor Internal (IAG)",
    desc: "Internal Audit Group pengawas kepatuhan hukum, forensik audit trail permanen, rekam jejak versi, dan kepatuhan retensi No-DELETE.",
    outsideCatalog: 0,
  },
  {
    id: "pengawas_syariah",
    name: "Dewan Pengawas Syariah (DPS)",
    desc: "Peninjau kepatuhan syariah terhadap klausul akad kerja sama dan instrumen perjanjian kemitraan BSI Maslahat.",
    outsideCatalog: 0,
  },
  {
    id: "partner_pic",
    name: "PIC Mitra Kemitraan (Eksternal)",
    desc: "Narahubung terdaftar pihak mitra kerja sama untuk koordinasi verifikasi dokumen prasyarat dan konfirmasi masa berlaku.",
    outsideCatalog: 0,
  },
  {
    id: "guest",
    name: "Reviewer Tamu (Read-Only)",
    desc: "Akses peninjau tamu sementara tanpa wewenang mutasi data kontrak maupun dokumen.",
    outsideCatalog: 0,
  },
  {
    id: "non_active",
    name: "User Non-Aktif / Tersuspensi",
    desc: "Akun non-aktif tanpa hak akses sistem CRS Maslahat.",
    outsideCatalog: 0,
  },
];

// 76 Detailed Catalog Items aligned with CRS BRD, Technical Specs, and APIs
export const RBAC_CATALOG_ITEMS = [
  // 1. PKS & KONTRAK (8 items)
  {
    id: 1,
    module: "PKS & KONTRAK",
    name: "Inisiasi / Pengajuan Draf PKS Baru",
    code: "contract:create",
    roles: ["super_admin", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "bu_pgg", "bu_cag", "bu_idg", "bu_wag", "bu_smg", "bu_fsg", "bu_leg", "bu_csg", "bu_hcg", "bu_bcg", "bu_edg"],
  },
  {
    id: 2,
    module: "PKS & KONTRAK",
    name: "Lihat Repositori Kontrak Unit Sendiri (Tenant Isolation)",
    code: "contract:read_own",
    roles: ["business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "bu_pgg", "bu_cag", "bu_idg", "bu_wag", "bu_smg", "bu_fsg", "bu_leg", "bu_csg", "bu_hcg", "bu_bcg", "bu_edg"],
  },
  {
    id: 3,
    module: "PKS & KONTRAK",
    name: "Lihat Seluruh Portofolio Kontrak Lintas Unit Kerja",
    code: "contract:read_all",
    roles: ["super_admin", "legal_officer", "management", "auditor_internal", "pengawas_syariah"],
  },
  {
    id: 4,
    module: "PKS & KONTRAK",
    name: "Koreksi Metadata Komersial (Drafting / Revisi)",
    code: "contract:update_meta",
    roles: ["super_admin", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "bu_pgg", "bu_cag", "bu_idg", "bu_wag", "bu_smg", "bu_fsg"],
  },
  {
    id: 5,
    module: "PKS & KONTRAK",
    name: "Kirim Draf PKS ke Antrean Telaah Legal (Submit for Review)",
    code: "contract:submit_review",
    roles: ["business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "bu_pgg", "bu_cag", "bu_idg", "bu_wag", "bu_smg", "bu_fsg"],
  },
  {
    id: 6,
    module: "PKS & KONTRAK",
    name: "Tarik Kembali Draf PKS (Recall Sebelum Direviu)",
    code: "contract:recall_draft",
    roles: ["business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "bu_pgg", "bu_cag", "bu_idg", "bu_wag", "bu_smg", "bu_fsg"],
  },
  {
    id: 7,
    module: "PKS & KONTRAK",
    name: "Buka Lembar Rincian Detail Metadata & Partner PIC",
    code: "contract:detail_sheet",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "bu_pgg", "management", "auditor_internal"],
  },
  {
    id: 8,
    module: "PKS & KONTRAK",
    name: "Pemantauan Jejak Alur Siklus Status Kontrak (Timeline)",
    code: "contract:timeline_view",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "bu_pgg", "management", "auditor_internal"],
  },

  // 2. DOKUMEN & VERSI (7 items)
  {
    id: 9,
    module: "DOKUMEN & VERSI",
    name: "Unggah Naskah Draf Perjanjian Word (.docx)",
    code: "doc:upload_draft_docx",
    roles: ["super_admin", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "bu_pgg", "bu_cag"],
  },
  {
    id: 10,
    module: "DOKUMEN & VERSI",
    name: "Unggah Dokumen Scan Bertandatangan Basah (.pdf/.jpg)",
    code: "doc:upload_signed_scan",
    roles: ["business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "legal_officer"],
  },
  {
    id: 11,
    module: "DOKUMEN & VERSI",
    name: "Unduh Dokumen Berkas Asli Repositori",
    code: "doc:download_original",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "management", "auditor_internal"],
  },
  {
    id: 12,
    module: "DOKUMEN & VERSI",
    name: "Pratinjau Teks Dokumen Inline Tanpa Unduh",
    code: "doc:preview_inline_text",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "management", "auditor_internal"],
  },
  {
    id: 13,
    module: "DOKUMEN & VERSI",
    name: "Akses Riwayat Versi Dokumen (v1.0, v1.1, Final)",
    code: "doc:version_history",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "management", "auditor_internal"],
  },
  {
    id: 14,
    module: "DOKUMEN & VERSI",
    name: "Ekstraksi Otomatis Metadata Berkas .docx (REQ-01)",
    code: "doc:extract_metadata_docx",
    roles: ["super_admin", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng"],
  },
  {
    id: 15,
    module: "DOKUMEN & VERSI",
    name: "Validasi Integritas Ukuran & Format File (Maksimal 25MB)",
    code: "doc:file_integrity_check",
    roles: ["super_admin", "legal_officer", "business_unit"],
  },

  // 3. LEGAL & COMPLIANCE (8 items)
  {
    id: 16,
    module: "LEGAL & COMPLIANCE",
    name: "Ambil Alih Draf Masuk (Intake Legal Review)",
    code: "legal:intake_pickup",
    roles: ["super_admin", "legal_officer"],
  },
  {
    id: 17,
    module: "LEGAL & COMPLIANCE",
    name: "Persetujuan Legalitas Draf (Ready for Signature)",
    code: "legal:approve_signature",
    roles: ["legal_officer"],
  },
  {
    id: 18,
    module: "LEGAL & COMPLIANCE",
    name: "Permintaan Perbaikan Draf / Klausul Hukum (Revision Required)",
    code: "legal:request_revision",
    roles: ["legal_officer"],
  },
  {
    id: 19,
    module: "LEGAL & COMPLIANCE",
    name: "Penolakan Berkas Langsung pada Tahap Intake (Reject at Intake)",
    code: "legal:reject_at_intake",
    roles: ["legal_officer"],
  },
  {
    id: 20,
    module: "LEGAL & COMPLIANCE",
    name: "Verifikasi Keaslian Fisik Scan Tandatangan (Final Verification)",
    code: "legal:verify_signed_pks",
    roles: ["legal_officer"],
  },
  {
    id: 21,
    module: "LEGAL & COMPLIANCE",
    name: "Aktivasi Resmi Dokumen PKS (Signed & Active Gate)",
    code: "legal:activate_contract",
    roles: ["legal_officer"],
  },
  {
    id: 22,
    module: "LEGAL & COMPLIANCE",
    name: "Pengisian Catatan Legalitas (Legal Remarks & Advice)",
    code: "legal:update_remarks",
    roles: ["legal_officer"],
  },
  {
    id: 23,
    module: "LEGAL & COMPLIANCE",
    name: "Penegakan State-based & Column-Level Lock (BRD Rule 3)",
    code: "legal:enforce_state_lock",
    roles: ["super_admin", "legal_officer"],
  },

  // 4. DUAL REVIEW MODE (6 items)
  {
    id: 24,
    module: "DUAL REVIEW MODE",
    name: "Akses Layar Telaah Ganda Side-by-Side (Digital & Scan)",
    code: "review:dual_screen_access",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "management"],
  },
  {
    id: 25,
    module: "DUAL REVIEW MODE",
    name: "Tulis Catatan & Masukan Pasal pada Naskah Kontrak",
    code: "review:comment_create",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng"],
  },
  {
    id: 26,
    module: "DUAL REVIEW MODE",
    name: "Baca Utas Diskusi & Evaluasi Pembahasan Klausul",
    code: "review:comment_read",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "management", "auditor_internal"],
  },
  {
    id: 27,
    module: "DUAL REVIEW MODE",
    name: "Tandai Poin Catatan Diskusi Telah Terselesaikan (Resolve)",
    code: "review:comment_resolve",
    roles: ["super_admin", "legal_officer"],
  },
  {
    id: 28,
    module: "DUAL REVIEW MODE",
    name: "Komparasi Visual Naskah Draf vs Scan Berkas Bertandatangan",
    code: "review:compare_versions",
    roles: ["super_admin", "legal_officer", "management"],
  },
  {
    id: 29,
    module: "DUAL REVIEW MODE",
    name: "Ekspor Ringkasan Catatan Legalitas Hasil Telaah Ganda",
    code: "review:export_notes",
    roles: ["super_admin", "legal_officer", "management"],
  },

  // 5. WATERMARKING ENGINE (5 items)
  {
    id: 30,
    module: "WATERMARKING ENGINE",
    name: "Penyematan Otomatis Stempel 'DRAFT - HASIL REVIU LEGAL' (REQ-03)",
    code: "watermark:auto_injection",
    roles: ["super_admin", "legal_officer"],
  },
  {
    id: 31,
    module: "WATERMARKING ENGINE",
    name: "Pencatatan Event WATERMARK_INJECTED pada Jejak Audit",
    code: "watermark:audit_log_event",
    roles: ["super_admin", "legal_officer", "auditor_internal"],
  },
  {
    id: 32,
    module: "WATERMARKING ENGINE",
    name: "Render Overlay Diagonal 45 Derajat Opasitas 30% pada PDF",
    code: "watermark:pdf_overlay_engine",
    roles: ["super_admin", "legal_officer"],
  },
  {
    id: 33,
    module: "WATERMARKING ENGINE",
    name: "Mekanisme Failsafe Proteksi Berkas JPG/PNG via Pillow Engine",
    code: "watermark:image_failsafe",
    roles: ["super_admin", "legal_officer"],
  },
  {
    id: 34,
    module: "WATERMARKING ENGINE",
    name: "Inspeksi Integritas Watermark pada Penampil Berkas Digital",
    code: "watermark:verify_stamp",
    roles: ["super_admin", "legal_officer", "management", "auditor_internal"],
  },

  // 6. SMART GUIDELINES (7 items)
  {
    id: 35,
    module: "SMART GUIDELINES",
    name: "Buka Modal Panduan Cerdas Syarat Legalitas Mitra (REQ-02)",
    code: "guide:view_modal",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "bu_cag", "bu_pgg", "partner_pic"],
  },
  {
    id: 36,
    module: "SMART GUIDELINES",
    name: "Matriks Prasyarat Yayasan (Akta, AHU, AD/ART, SK Pengurus)",
    code: "guide:matrix_yayasan",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "partner_pic"],
  },
  {
    id: 37,
    module: "SMART GUIDELINES",
    name: "Matriks Prasyarat Perusahaan PT (Akta, SK Kemenkumham, NPWP, NIB)",
    code: "guide:matrix_pt",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_cag", "partner_pic"],
  },
  {
    id: 38,
    module: "SMART GUIDELINES",
    name: "Matriks Prasyarat Koperasi (Akta, SK Menteri Koperasi, AD/ART)",
    code: "guide:matrix_koperasi",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_rng", "partner_pic"],
  },
  {
    id: 39,
    module: "SMART GUIDELINES",
    name: "Matriks Prasyarat Instansi Pemerintah (SK Penunjukan, DIPA Anggaran)",
    code: "guide:matrix_instansi",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_pgg", "partner_pic"],
  },
  {
    id: 40,
    module: "SMART GUIDELINES",
    name: "Matriks Prasyarat DKM Masjid (SK DKM, KTP Ketua, Surat Domisili)",
    code: "guide:matrix_dkm",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_dfg", "bu_wag", "partner_pic"],
  },
  {
    id: 41,
    module: "SMART GUIDELINES",
    name: "Matriks Prasyarat Perkumpulan & Perorangan (Akta, KTP, NPWP)",
    code: "guide:matrix_perkumpulan",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_smg", "partner_pic"],
  },

  // 7. REMINDER & KEDALUWARSA (6 items)
  {
    id: 42,
    module: "REMINDER & KEDALUWARSA",
    name: "Otomasi Pengingat Masa Kedaluwarsa H-60 (REQ-05)",
    code: "reminder:scheduler_h60",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "management"],
  },
  {
    id: 43,
    module: "REMINDER & KEDALUWARSA",
    name: "Otomasi Pengingat Masa Kedaluwarsa H-30 (REQ-05)",
    code: "reminder:scheduler_h30",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "management"],
  },
  {
    id: 44,
    module: "REMINDER & KEDALUWARSA",
    name: "Early Warning Pengingat Masa Kedaluwarsa H-7 (REQ-05)",
    code: "reminder:scheduler_h7",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "management"],
  },
  {
    id: 45,
    module: "REMINDER & KEDALUWARSA",
    name: "Penerimaan In-App Notifications & Counter Lonceng Pengingat",
    code: "reminder:in_app_alert",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "management"],
  },
  {
    id: 46,
    module: "REMINDER & KEDALUWARSA",
    name: "Pengiriman Notifikasi Email Resmi Berdesain via Gateway SMTP",
    code: "reminder:email_smtp",
    roles: ["super_admin", "legal_officer", "business_unit"],
  },
  {
    id: 47,
    module: "REMINDER & KEDALUWARSA",
    name: "Trigger Manual Cron Job Pengecekan Kedaluwarsa Kontrak",
    code: "reminder:manual_trigger",
    roles: ["super_admin"],
  },

  // 8. DASBOR & ANALITIK (6 items)
  {
    id: 48,
    module: "DASBOR & ANALITIK",
    name: "Akses 4 Kartu KPI Dasbor (Aktif, Menunggu Review, Segera Berakhir, Kedaluwarsa)",
    code: "analytics:kpi_summary",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "bu_rng", "management", "auditor_internal"],
  },
  {
    id: 49,
    module: "DASBOR & ANALITIK",
    name: "Analitik Grafik Distribusi PKS Berdasarkan Unit Kerja (Owning BU)",
    code: "analytics:chart_by_bu",
    roles: ["super_admin", "legal_officer", "management", "auditor_internal"],
  },
  {
    id: 50,
    module: "DASBOR & ANALITIK",
    name: "Analitik Grafik Sebaran 8 Tahapan Status Siklus Kontrak",
    code: "analytics:chart_by_status",
    roles: ["super_admin", "legal_officer", "management", "auditor_internal"],
  },
  {
    id: 51,
    module: "DASBOR & ANALITIK",
    name: "Analitik Distribusi Sebaran 7 Tipe Lembaga Kemitraan",
    code: "analytics:chart_by_institution",
    roles: ["super_admin", "legal_officer", "management", "auditor_internal"],
  },
  {
    id: 52,
    module: "DASBOR & ANALITIK",
    name: "Analisis Tren Bulanan Pertumbuhan & Kedaluwarsa Kontrak PKS",
    code: "analytics:chart_monthly_trend",
    roles: ["super_admin", "legal_officer", "management", "auditor_internal"],
  },
  {
    id: 53,
    module: "DASBOR & ANALITIK",
    name: "Monitoring Akumulasi Nilai Rupiah Portofolio Kerja Sama",
    code: "analytics:portfolio_value",
    roles: ["super_admin", "legal_officer", "management"],
  },

  // 9. LAPORAN & EKSPOR (5 items)
  {
    id: 54,
    module: "LAPORAN & EKSPOR",
    name: "Ekspor Rekapitulasi Portofolio PKS ke Spreadsheet (.xlsx)",
    code: "report:export_excel",
    roles: ["super_admin", "legal_officer", "management", "auditor_internal"],
  },
  {
    id: 55,
    module: "LAPORAN & EKSPOR",
    name: "Ekspor Ringkasan Portofolio Dokumen Cetak Landscape (.pdf)",
    code: "report:export_pdf",
    roles: ["super_admin", "legal_officer", "management", "auditor_internal"],
  },
  {
    id: 56,
    module: "LAPORAN & EKSPOR",
    name: "Rekapitulasi Portofolio Berdasarkan Filter Rentang Tanggal",
    code: "report:filter_by_date",
    roles: ["super_admin", "legal_officer", "management", "auditor_internal"],
  },
  {
    id: 57,
    module: "LAPORAN & EKSPOR",
    name: "Rekapitulasi Khusus Portofolio Mitra Yayasan & Pemerintah",
    code: "report:filter_by_institution",
    roles: ["super_admin", "legal_officer", "management", "auditor_internal"],
  },
  {
    id: 58,
    module: "LAPORAN & EKSPOR",
    name: "Kustomisasi Parameter Bidang Kolom Ekspor Laporan",
    code: "report:custom_query",
    roles: ["super_admin"],
  },

  // 10. TATA KELOLA PENGGUNA (6 items)
  {
    id: 59,
    module: "TATA KELOLA PENGGUNA",
    name: "Pembuatan Akun Pengguna Staf Maslahat Baru",
    code: "user:create_account",
    roles: ["super_admin"],
  },
  {
    id: 60,
    module: "TATA KELOLA PENGGUNA",
    name: "Melihat Direktori Daftar Akun Staf & Afiliasi Unit Kerja",
    code: "user:read_directory",
    roles: ["super_admin", "management", "auditor_internal"],
  },
  {
    id: 61,
    module: "TATA KELOLA PENGGUNA",
    name: "Penugasan Peran (Admin, BU, Legal, Management)",
    code: "user:assign_role",
    roles: ["super_admin"],
  },
  {
    id: 62,
    module: "TATA KELOLA PENGGUNA",
    name: "Penugasan Afiliasi Unit Kerja (Owning BU CRG, DFG, RNG, dll)",
    code: "user:assign_bu",
    roles: ["super_admin"],
  },
  {
    id: 63,
    module: "TATA KELOLA PENGGUNA",
    name: "Reset Kata Sandi & Kredensial Pengguna",
    code: "user:reset_credentials",
    roles: ["super_admin"],
  },
  {
    id: 64,
    module: "TATA KELOLA PENGGUNA",
    name: "Aktivasi & Penonaktifan Hak Akses Pengguna Sistem",
    code: "user:toggle_status",
    roles: ["super_admin"],
  },
  {
    id: "rbac:access_menu",
    module: "TATA KELOLA PENGGUNA",
    name: "Akses Tampilan Menu Navigasi & Konfigurasi RBAC (Sidebar ON/OFF)",
    code: "rbac:access_menu",
    desc: "Mengizinkan kemunculan grup menu navigasi RBAC pada bilah samping (sidebar) dan akses ke layar Role & Akses, Perbandingan, dan Katalog.",
    roles: ["super_admin", "management"],
  },

  // 11. AUDIT TRAIL & FORENSIK (6 items)
  {
    id: 65,
    module: "AUDIT TRAIL & FORENSIK",
    name: "Akses Jejak Audit per Kontrak Permanen (REQ-06)",
    code: "audit:contract_event_log",
    roles: ["super_admin", "legal_officer", "business_unit", "bu_crg", "bu_dfg", "bu_mcg", "management", "auditor_internal"],
  },
  {
    id: 66,
    module: "AUDIT TRAIL & FORENSIK",
    name: "Akses Log Audit Sistem Tingkat HTTP Keseluruhan (System Audit)",
    code: "audit:system_http_log",
    roles: ["super_admin", "auditor_internal"],
  },
  {
    id: 67,
    module: "AUDIT TRAIL & FORENSIK",
    name: "Penegakan Kebijakan Larangan Hapus Berkas (No DELETE 405 Method)",
    code: "audit:enforce_no_delete",
    roles: ["super_admin", "auditor_internal"],
  },
  {
    id: 68,
    module: "AUDIT TRAIL & FORENSIK",
    name: "Inspeksi Sesi Kriptografis JWT Sliding Session 15 Menit Inaktivitas",
    code: "audit:sliding_session",
    roles: ["super_admin"],
  },
  {
    id: 69,
    module: "AUDIT TRAIL & FORENSIK",
    name: "Verifikasi Integritas Jejak Mutasi Data Dokumen Kemitraan",
    code: "audit:tamper_proof",
    roles: ["super_admin", "auditor_internal"],
  },
  {
    id: 70,
    module: "AUDIT TRAIL & FORENSIK",
    name: "Inspeksi Konfigurasi Kebijakan Keamanan RBAC (Security Policy)",
    code: "audit:security_policy",
    roles: ["super_admin", "legal_officer", "management", "auditor_internal"],
  },

  // 12. SISTEM & INTEGRASI (5 items)
  {
    id: 71,
    module: "SISTEM & INTEGRASI",
    name: "Pemantauan Status Kesiapan Server & Konektivitas Database Motor",
    code: "sys:health_check",
    roles: ["super_admin", "auditor_internal"],
  },
  {
    id: 72,
    module: "SISTEM & INTEGRASI",
    name: "Konfigurasi Media Penyimpanan Berkas Lokal / Cloud S3 Storage",
    code: "sys:storage_driver",
    roles: ["super_admin"],
  },
  {
    id: 73,
    module: "SISTEM & INTEGRASI",
    name: "Manajemen Secret Key Webhook Cron Eksternal",
    code: "sys:webhook_cron_key",
    roles: ["super_admin"],
  },
  {
    id: 74,
    module: "SISTEM & INTEGRASI",
    name: "Menjalankan Worker Script Eksternal Otomasi Pemeliharaan",
    code: "sys:custom_cron_runner",
    roles: ["super_admin"],
  },
  {
    id: 75,
    module: "SISTEM & INTEGRASI",
    name: "Akses Dokumentasi Interaktif OpenAPI / Swagger CRS",
    code: "sys:api_docs_access",
    roles: ["super_admin", "auditor_internal"],
  },
];

// Dynamically compute exact stats and role permissions to guarantee consistency across all 3 pages
export const RBAC_ROLES = RAW_ROLES.map((r) => {
  const roleItems = RBAC_CATALOG_ITEMS.filter((item) => item.roles.includes(r.id));
  const modulesSet = new Set(roleItems.map((item) => item.module));

  return {
    ...r,
    accessCount: roleItems.length,
    moduleCount: modulesSet.size,
    outsideCatalog: r.outsideCatalog || 0,
  };
});
